name: Labeled
on:
  pull_request:
    types: labeled

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      TOTAL: ${{ steps.parse_json.outputs.TOTAL }}
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        if: ${{(github.event.label.name == 'qodana') && (github.event.label.name == 'テスト')}}
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: qodana.yml
      - uses: JetBrains/qodana-action@v2023.2
        with:
          args: --baseline,./qodana-report/results/qodana.sarif.json
          upload-result: true
      - name: Get Qodana Result
        if: ${{(github.event.label.name == 'qodana') && (github.event.label.name == 'テスト')}}
        id: parse_json
        run: echo "TOTAL="$(cat ${{ runner.temp }}/qodana/results/report/results/metaInformation.json | jq -r '.total')"" >> $GITHUB_OUTPUT
      - name: Output
        if: ${{(github.event.label.name == 'qodana') && (github.event.label.name == 'テスト')}}
        run: echo "${{steps.parse_json.outputs.TOTAL}} counts"
      - name: Deploy to GitHub Pages
        if: ${{(github.event.label.name == 'qodana') && (github.event.label.name == 'テスト')}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./qodana
      - name: Comment to Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '解析が完了しました\n https://ike04.github.io/Qodana_Sample/qodana/ '
            })
  job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Output2
        if: ${{(github.event.label.name == 'qodana') && (github.event.label.name == 'テスト')}}
        run: echo "${{needs.build.outputs.TOTAL}} counts"