name: Qodana

on:
  push:
    branches: [ fix_yml ]
    paths-ignore: [ '**.md', '**.MD' ]
  pull_request:
    branches: [ fix_yml ]
    paths-ignore: [ '**.md', '**.MD' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      TOTAL: ${{ steps.parse_json.outputs.TOTAL }}
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_number: 75
      - name: path
        run: echo tree "${{ runner.temp }}/qodana/results/qodana.sarif.json"

      - uses: JetBrains/qodana-action@v2023.1.0
        with:
          args: --baseline,${{ runner.temp }}/qodana/results/qodana.sarif.json
      - name: Get Qodana Result
        id: parse_json
        run: echo "TOTAL="$(cat ${{ runner.temp }}/qodana/results/report/results/metaInformation.json | jq -r '.total')"" >> $GITHUB_OUTPUT
      - name: Output
        run: echo "${{steps.parse_json.outputs.TOTAL}} counts"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./qodana
  job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Output2
        run: echo "${{needs.build.outputs.TOTAL}} counts"