name: Qodana

on:
  push:
    branches: [ fix_yml ]
    paths-ignore: [ '**.md', '**.MD' ]
  pull_request:
    branches: [ fix_yml ]
    paths-ignore: [ '**.md', '**.MD' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: JetBrains/qodana-action@v2022.3.0
        with:
          args: --baseline,qodana.sarif.json
        run: echo $GITHUB_STEP_SUMMARY
      - name: Get Qodana Result
        id: parse_json
        run: echo "$(cat ${{ runner.temp }}/qodana/results/report/results/metaInformation.json | jq -r '.total')"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./qodana