name: Qodana

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      TOTAL: ${{ steps.parse_json.outputs.TOTAL }}
    steps:
      - uses: actions/checkout@v3
      - name: run number with offset
        env:
          NUM: ${{ github.run_number }}
        run: |
          echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$(($NUM - 1))" >> $GITHUB_ENV
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_number: ${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}
          if_no_artifact_found: ignore
      - uses: JetBrains/qodana-action@v2023.2
        with:
          args: --baseline,./qodana-report/results/qodana.sarif.json
          upload-result: true
      - name: Get Qodana Result
        id: parse_json
        run: echo "TOTAL="$(cat ${{ runner.temp }}/qodana/results/report/results/metaInformation.json | jq -r '.total')"" >> $GITHUB_OUTPUT
      - name: Output
        run: echo "${{steps.parse_json.outputs.TOTAL}} counts"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./qodana
  job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Output2
        run: echo "${{needs.build.outputs.TOTAL}} counts"