name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Skip duplicate actions
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          cancel_others: true

      - name: Set up java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
        continue-on-error: true

      - name: Initialize Gradle Project
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build

      - name: 'Run Qodana'
        uses: JetBrains/qodana-action@v2022.3.0
        with:
          args: >
            --env,BUGLY_APPID=${{ secrets.BUGLY_APPID }}
          use-caches: false
